import { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useMemo } from "react";
import { H1, H2 } from "../../components/Headings";
import { CardSolution } from "../../components/solutions/CardSolution";
import { GridSolution } from "../../components/solutions/GridSolution";
import { useChain } from "../../hooks/useChain";
import CHAINS_JSON from '../../jsons/chains.json'
import { L1Chain } from "../../types/constants";
import { ViewChain } from "../../views/ViewChain";
import { ViewSolution } from "../../views/ViewSolution";

const Chain: NextPage = () => {
    const { chain, solution, isSolution } = useChain()


    return (
        <>
        <Head>
            <title>L2 Planet - Newsletter</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        {chain && !isSolution ? <ViewChain chain={chain}/> : solution && <ViewSolution solution={solution}/>}
        </>
    )
}

export default Chain
