import { NextPage } from "next"
import Head from "next/head"
import { wrapn } from "wrapn"
import { PrimaryInfoCommon } from "../../components/chains/PrimaryInfoCommon"
import { CardSolution, Grid4CardsCommon } from "../../components/chains/common"
import { useChain } from "../../hooks/useChain"
import { ViewChain } from "../../views/ViewChain"

const Chain: NextPage = () => {
    const chain = useChain()

    return (
        <>
            <Head>
                <title>L2 Planet - {chain?.name || 'Chain'}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Div>
                {chain && <ViewChain chain={chain}/>}
            </Div>
        </>
    )
}

export default Chain

const Div = wrapn('div')`
    flex flex-col
    gap-y-6
`