import { NextPage } from "next";
import Head from "next/head";
import { CardAbout } from "../components/about/CardAbout";
import { GridAbout } from "../components/about/GridAbout";
import { FlexCol } from "../components/Divs";
import { H1, H2 } from "../components/Headings";
import { IconFeed } from "../components/icons/IconFeed";
import { PAbout } from "../components/Paragraphs";

/* eslint-disable react/no-unescaped-entities */

const About: NextPage = () => {
    return (
        <>
        <Head>
            <title>L2 Planet - About</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <FlexCol>
            <H2>About Us</H2>
            <PAbout>Let's learn about us!</PAbout>
        </FlexCol>
        <GridAbout>
            <CardAbout
                Icon={IconFeed}
                title='Giving Information'
                text='We write newsletters about the state of L2 solutions to make you informed.'
            />
            <CardAbout
                Icon={IconFeed}
                title='Giving Information'
                text='We write newsletters about the state of L2 solutions to make you informed.'
            />
            <CardAbout
                Icon={IconFeed}
                title='Giving Information'
                text='We write newsletters about the state of L2 solutions to make you informed.'
            />
            <CardAbout
                Icon={IconFeed}
                title='Giving Information'
                text='We write newsletters about the state of L2 solutions to make you informed.'
            />
        </GridAbout>
        </>
    )
}

export default About