import type { NextPage } from 'next'
import Head from 'next/head'
import { GridChain } from '../components/chains/GridChain'
import { CardChain } from '../components/chains/CardChain'
import { H1, H2 } from '../components/Headings'
import { ImageBlurIndigo } from '../components/Images'
import { useApi } from '../contexts/ApiContext'

const Home: NextPage = () => {
    const { data } = useApi()

    return (
    <>
        <Head>
            <title>L2 Planet</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <H1>Choose Your Path</H1>
        <GridChain>
            {data && Object.entries(data.chains).map(([chainId, value]) => value && <CardChain key={chainId} chain={value} chainId={chainId}/>)}
        </GridChain>
    </>
    )
}

export default Home
