import type { NextPage } from 'next'
import Head from 'next/head'
import { Blocker } from '../components/Blocker'
import { GridChain } from '../components/chains/GridChain'
import { CardChain } from '../components/chains/CardChain'
import { Block } from '../types/constants'
import { H1, H2 } from '../components/Headings'
import Image from 'next/image'
import { ImageBlurIndigo } from '../components/Images'
import {  } from '../components/Paragraphs'
import CHAINS_JSON from '../jsons/chains.json'

const Home: NextPage = () => {
    return (
    <>
        <Head>
            <title>L2 Planet</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <ImageBlurIndigo/>
        <H1>Chose Your Path</H1>
        <GridChain>
            {Object.entries(CHAINS_JSON).map(([key, val]) =>  <CardChain key={key} id={key} chain={val}/>)}
        </GridChain>
    </>
    )
}

export default Home
