import { NextPage } from "next";
import Head from "next/head";

const Stats: NextPage = () => {
    return (
        <>
        <Head>
            <title>L2 Planet - Stats</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        
        
        </>
    )
}

export default Stats