import { NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";
import { Editor } from "../components/editor";
import { PhantomProvider } from "../contexts/Phantom";
import { WritersView } from "../views";

const Writers: NextPage = () => {

    return (
        <PhantomProvider>
            <Head>
                <title>L2 Planet - Writers</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Editor/>
        </PhantomProvider>
    )
}

export default Writers