import { NextPage } from "next";
import Head from "next/head";
import { wrapn } from "wrapn";
import { SecondaryInfoCommon } from "../../components/chains/SecondaryInfoCommon";
import { useProject } from "../../hooks/useProject";
import { useSolution } from "../../hooks/useSolution";
import { ViewProject } from "../../views/ViewProject";
import { ViewProjectsOn } from "../../views/ViewProjectsOn";

const Project: NextPage = () => {

    const solution = useSolution()

    return (
        <>
            <Head>
                <title>L2 Planet - Projects on {solution?.name || 'Solution'}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Div>
                {solution && <ViewProjectsOn solution={solution}/>}
            </Div>
        </>
    )
}


export default Project


const Div = wrapn('div')`
    flex flex-col
    gap-y-10 sm:gap-y-12 md:gap-y-14 lg:gap-y-16
`