import { NextPage } from "next";
import Head from "next/head";
import { wrapn } from "wrapn";
import { SecondaryInfoCommon } from "../../components/chains/SecondaryInfoCommon";
import { useProject } from "../../hooks/useProject";
import { ViewProject } from "../../views/ViewProject";

const Project: NextPage = () => {

    const project = useProject()

    return (
        <>
            <Head>
                <title>L2 Planet - {project?.name || 'Project'}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Div>
                {project && <ViewProject project={project}/>}
            </Div>
        </>
    )
}


export default Project


const Div = wrapn('div')`
    flex flex-col
    gap-y-10 sm:gap-y-12 md:gap-y-14 lg:gap-y-16
`