import { NextPage } from "next"
import Head from "next/head"
import { wrapn } from "wrapn"
import { PrimaryInfoCommon } from "../../components/chains/PrimaryInfoCommon"
import { CardProject, Grid4CardsCommon } from "../../components/chains/common"
import { useSolution } from "../../hooks/useSolution"
import { useEffect } from "react"
import { ViewSolution } from "../../views/ViewSolution"

const Solution: NextPage = () => {
    const solution = useSolution()

    return (
        <>
            <Head>
                <title>L2 Planet - {solution?.name || 'Chain'}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Div>
                {solution && <ViewSolution solution={solution}/>}
            </Div>
        </>
    )
}


export default Solution


const Div = wrapn('div')`
    flex flex-col
    gap-y-6
`